In [1]:
#By Kashish Bhagat
import numpy as np
import pandas as pd
import keras


np.random.seed(2)

Using TensorFlow backend.


In [2]:
pd.pandas.set_option('display.max_columns',None)

In [3]:
data=pd.read_csv('creditcard.csv')

In [4]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [5]:
#Data Exploration 
#PReprocessing

In [6]:
from sklearn.preprocessing import StandardScaler
data['normalized']=StandardScaler().fit_transform(data['Amount'].values.reshape(-1,1))

In [7]:
data=data.drop(['Amount'],axis=1)

In [8]:
data=data.drop(['Time'],axis=1)

In [9]:
data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Class  normalized  
0      0    0.244964  
1      0   -0.342475  
2      0    1.160686  
3      0    0.140534  
4      0   -0.073403

In [10]:
data.shape

(284807, 30)

In [11]:
X=data.iloc[:,data.columns!='Class']
y=data.iloc[:,data.columns=='Class']

In [12]:
y.head()

Class
0      0
1      0
2      0
3      0
4      0

In [13]:
#Spliiting The Dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [14]:
print(X_train.shape)
print(X_test.shape)

(199364, 29)
(85443, 29)


In [15]:
X_train=np.array(X_train)
X_test=np.array(X_test)
y_train=np.array(y_train)
y_test=np.array(y_test)


In [16]:
#Deep Neural Network
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout


In [17]:
model=Sequential([
    Dense(units=16,input_dim=29,activation='relu'),
    Dense(units=24,activation='relu'),
    Dropout(0.5),
    Dense(20,activation='relu'),
    Dense(24,activation='relu'),
    Dense(units=1,activation='sigmoid')
])


In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                480       
_________________________________________________________________
dense_2 (Dense)              (None, 24)                408       
_________________________________________________________________
dropout_1 (Dropout)          (None, 24)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 20)                500       
_________________________________________________________________
dense_4 (Dense)              (None, 24)                504       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 25        
Total params: 1,917
Trainable params: 1,917
Non-trainable params: 0
____________________________________________________

In [19]:
#Training
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=15,epochs=5)

Epoch 1/5
199364/199364 [==============================] - 15s 75us/step - loss: 0.0096 - accuracy: 0.9979
Epoch 2/5
199364/199364 [==============================] - 17s 86us/step - loss: 0.0038 - accuracy: 0.9994
Epoch 3/5
199364/199364 [==============================] - 18s 90us/step - loss: 0.0035 - accuracy: 0.9993
Epoch 4/5
199364/199364 [==============================] - 19s 94us/step - loss: 0.0033 - accuracy: 0.9994
Epoch 5/5
199364/199364 [==============================] - 18s 90us/step - loss: 0.0031 - accuracy: 0.9994


In [21]:
score=model.evaluate(X_test,y_test)

85443/85443 [==============================] - 1s 16us/step


In [22]:
print(score)

[0.0036733564825058417, 0.999426543712616]


In [23]:
y_pred=model.predict(X_test)
y_test=pd.DataFrame(y_test)

In [24]:
y_pred

array([[4.9004626e-05],
       [4.2122905e-05],
       [1.2728925e-03],
       ...,
       [1.6490878e-05],
       [6.2295435e-06],
       [4.5550491e-06]], dtype=float32)

In [25]:
y_test

0
0      0
1      0
2      0
3      0
4      0
...   ..
85438  0
85439  0
85440  0
85441  0
85442  0

[85443 rows x 1 columns]

In [27]:
y_pred

array([[4.9004626e-05],
       [4.2122905e-05],
       [1.2728925e-03],
       ...,
       [1.6490878e-05],
       [6.2295435e-06],
       [4.5550491e-06]], dtype=float32)

In [28]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred.round())

In [29]:
cm

array([[85278,    18],
       [   31,   116]], dtype=int64)